-- =============================================================
-- MIGRATION v5 — SITE-WIDE ASSET / ICON LIBRARY  (already applied)
-- Upload an icon once and reuse it in any image field: cards,
-- KPIs, squads, section titles, the image editor…
-- Managed from the "Biblioteca" button in the builder.
-- =============================================================

create table if not exists public.assets (
  id         bigint generated by default as identity primary key,
  name       text not null default 'Sem nome',
  url        text not null,
  category   text not null default 'icon',   -- icon | hero | troop | building | other
  sort       integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists assets_cat_idx on public.assets (category, sort, id);

alter table public.assets enable row level security;
drop policy if exists "anon read assets"   on public.assets;
drop policy if exists "anon insert assets" on public.assets;
drop policy if exists "anon update assets" on public.assets;
drop policy if exists "anon delete assets" on public.assets;
create policy "anon read assets"   on public.assets for select using (true);
create policy "anon insert assets" on public.assets for insert with check (true);
create policy "anon update assets" on public.assets for update using (true) with check (true);
create policy "anon delete assets" on public.assets for delete using (true);

alter publication supabase_realtime add table public.assets;

-- Seeded with the icons already shipped in /public (see git history).
