-- =============================================================
-- MIGRATION v4 — EVENT PAGE BUILDER  (already applied)
-- A page is a single JSONB document:
--   { theme: {...}, header: [blocks], tabs: [{id,label,blocks}] }
-- Anyone with the /evento/editar link can edit (same open model
-- as the board itself).
-- =============================================================

create table if not exists public.event_pages (
  id         bigint generated by default as identity primary key,
  slug       text not null unique,
  title      text not null default 'Untitled event',
  doc        jsonb not null default '{"theme":{},"blocks":[]}'::jsonb,
  published  boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists event_pages_slug_idx on public.event_pages (slug);

drop trigger if exists event_pages_updated_at on public.event_pages;
create trigger event_pages_updated_at
before update on public.event_pages
for each row execute function public.set_updated_at();

alter table public.event_pages enable row level security;
drop policy if exists "anon read event pages"   on public.event_pages;
drop policy if exists "anon insert event pages" on public.event_pages;
drop policy if exists "anon update event pages" on public.event_pages;
drop policy if exists "anon delete event pages" on public.event_pages;
create policy "anon read event pages"   on public.event_pages for select using (true);
create policy "anon insert event pages" on public.event_pages for insert with check (true);
create policy "anon update event pages" on public.event_pages for update using (true) with check (true);
create policy "anon delete event pages" on public.event_pages for delete using (true);

-- ------- Version history: every save snapshots the previous doc -------
create table if not exists public.event_page_versions (
  id      bigint generated by default as identity primary key,
  page_id bigint not null,
  doc     jsonb not null,
  at      timestamptz not null default now()
);
create index if not exists event_page_versions_page_idx
  on public.event_page_versions (page_id, at desc);

create or replace function public.snapshot_event_page()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if NEW.doc is distinct from OLD.doc then
    insert into public.event_page_versions(page_id, doc) values (OLD.id, OLD.doc);
    delete from public.event_page_versions
     where id in (
       select id from public.event_page_versions
        where page_id = OLD.id order by at desc offset 50
     );
  end if;
  return NEW;
end; $$;

drop trigger if exists event_pages_snapshot on public.event_pages;
create trigger event_pages_snapshot
before update on public.event_pages
for each row execute function public.snapshot_event_page();

alter table public.event_page_versions enable row level security;
drop policy if exists "anon read page versions" on public.event_page_versions;
create policy "anon read page versions" on public.event_page_versions for select using (true);

alter publication supabase_realtime add table public.event_pages;

-- ------- Storage bucket for images / gifs / short videos -------
insert into storage.buckets (id, name, public, file_size_limit)
values ('event-assets', 'event-assets', true, 26214400)
on conflict (id) do update set public = true, file_size_limit = 26214400;

drop policy if exists "public read event assets" on storage.objects;
drop policy if exists "anon upload event assets" on storage.objects;
drop policy if exists "anon update event assets" on storage.objects;
drop policy if exists "anon delete event assets" on storage.objects;
create policy "public read event assets" on storage.objects
  for select using (bucket_id = 'event-assets');
create policy "anon upload event assets" on storage.objects
  for insert with check (bucket_id = 'event-assets');
create policy "anon update event assets" on storage.objects
  for update using (bucket_id = 'event-assets') with check (bucket_id = 'event-assets');
create policy "anon delete event assets" on storage.objects
  for delete using (bucket_id = 'event-assets');
