-- =============================================================
-- MIGRATION v8 — LINEUP CONFIRMATIONS  (already applied)
-- A player opens the event link and confirms their own slot.
-- Confirmation is open (no login), so a row is just a fact:
-- "this slot on this lineup was confirmed at this time".
-- =============================================================

create table if not exists public.lineup_confirmations (
  id           bigint generated by default as identity primary key,
  page_slug    text not null,
  block_id     text not null,          -- the lineup block's own id
  member_key   text not null,          -- 'm:<memberId>' or 'g:<guestId>'
  member_name  text not null default '',
  confirmed_at timestamptz not null default now(),
  unique (page_slug, block_id, member_key)
);

create index if not exists lineup_conf_page_idx
  on public.lineup_confirmations (page_slug, block_id);

alter table public.lineup_confirmations enable row level security;
drop policy if exists "anon read confirmations"   on public.lineup_confirmations;
drop policy if exists "anon insert confirmations" on public.lineup_confirmations;
drop policy if exists "anon delete confirmations" on public.lineup_confirmations;
create policy "anon read confirmations"   on public.lineup_confirmations for select using (true);
create policy "anon insert confirmations" on public.lineup_confirmations for insert with check (true);
create policy "anon delete confirmations" on public.lineup_confirmations for delete using (true);

alter publication supabase_realtime add table public.lineup_confirmations;
