-- =============================================================
-- DAD TROOPS INTEL — MIGRATION v3  ·  CHANGE / AUDIT LOG
-- Records every add / edit / remove on members automatically,
-- via a database trigger (captures changes from ANY device).
-- Run this ONCE in the Supabase SQL Editor.
-- =============================================================

-- ------- 1. Log table -------
create table if not exists public.member_logs (
  id bigint generated by default as identity primary key,
  member_id   bigint,
  member_name text,
  action      text not null,          -- 'insert' | 'update' | 'delete'
  changes     jsonb not null default '{}'::jsonb,
  at          timestamptz not null default now()
);

create index if not exists member_logs_at_idx on public.member_logs (at desc);

-- ------- 2. Trigger function (SECURITY DEFINER so it always writes) -------
create or replace function public.log_member_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  ch jsonb := '{}'::jsonb;
begin
  if (TG_OP = 'INSERT') then
    ch := jsonb_build_object(
      'inf_count',  NEW.inf_count,
      'cav_count',  NEW.cav_count,
      'arch_count', NEW.arch_count
    );
    insert into public.member_logs(member_id, member_name, action, changes)
      values (NEW.id, NEW.name, 'insert', ch);
    return NEW;

  elsif (TG_OP = 'UPDATE') then
    if NEW.name       is distinct from OLD.name       then ch := ch || jsonb_build_object('name',       jsonb_build_object('old', OLD.name,       'new', NEW.name)); end if;
    if NEW.avatar     is distinct from OLD.avatar     then ch := ch || jsonb_build_object('avatar',     jsonb_build_object('old', OLD.avatar,     'new', NEW.avatar)); end if;
    if NEW.inf_count  is distinct from OLD.inf_count  then ch := ch || jsonb_build_object('inf_count',  jsonb_build_object('old', OLD.inf_count,  'new', NEW.inf_count)); end if;
    if NEW.cav_count  is distinct from OLD.cav_count  then ch := ch || jsonb_build_object('cav_count',  jsonb_build_object('old', OLD.cav_count,  'new', NEW.cav_count)); end if;
    if NEW.arch_count is distinct from OLD.arch_count then ch := ch || jsonb_build_object('arch_count', jsonb_build_object('old', OLD.arch_count, 'new', NEW.arch_count)); end if;
    if ch <> '{}'::jsonb then
      insert into public.member_logs(member_id, member_name, action, changes)
        values (NEW.id, NEW.name, 'update', ch);
    end if;
    return NEW;

  elsif (TG_OP = 'DELETE') then
    ch := jsonb_build_object(
      'inf_count',  OLD.inf_count,
      'cav_count',  OLD.cav_count,
      'arch_count', OLD.arch_count
    );
    insert into public.member_logs(member_id, member_name, action, changes)
      values (OLD.id, OLD.name, 'delete', ch);
    return OLD;
  end if;
  return null;
end;
$$;

drop trigger if exists members_audit on public.members;
create trigger members_audit
after insert or update or delete on public.members
for each row execute function public.log_member_change();

-- ------- 3. Row Level Security: anon can READ the log (for /dados). -------
-- No insert/update/delete policy for anon — only the SECURITY DEFINER
-- trigger writes to it, so the history can't be tampered with via the API.
alter table public.member_logs enable row level security;
drop policy if exists "anon can read logs" on public.member_logs;
create policy "anon can read logs" on public.member_logs
  for select using (true);

-- ------- 4. Enable realtime so /dados updates live -------
alter publication supabase_realtime add table public.member_logs;
