-- =============================================================
-- DAD TROOPS INTELLIGENCE BOARD — SUPABASE INIT
-- =============================================================
-- Run this ENTIRE file once in the Supabase SQL Editor
-- (Dashboard → SQL Editor → New query → paste all → Run).
-- =============================================================

-- ------- 1. Table -------
create table if not exists public.members (
  id bigint generated by default as identity primary key,
  name text not null,
  power numeric(6,1) not null default 0,
  inf text not null default '-',
  cav text not null default '-',
  arc text not null default '-',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists members_power_idx on public.members (power desc);

-- ------- 2. updated_at trigger -------
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists members_updated_at on public.members;
create trigger members_updated_at
before update on public.members
for each row execute function public.set_updated_at();

-- ------- 3. Row Level Security (OPEN — anon can read + write) -------
alter table public.members enable row level security;

drop policy if exists "anon can read members" on public.members;
create policy "anon can read members" on public.members
for select using (true);

drop policy if exists "anon can insert members" on public.members;
create policy "anon can insert members" on public.members
for insert with check (true);

drop policy if exists "anon can update members" on public.members;
create policy "anon can update members" on public.members
for update using (true) with check (true);

drop policy if exists "anon can delete members" on public.members;
create policy "anon can delete members" on public.members
for delete using (true);

-- ------- 4. Enable realtime -------
alter publication supabase_realtime add table public.members;

-- ------- 5. Seed data (56 members from July 2026 poll) -------
-- Clears any existing data before seeding. Skip this if you want to preserve edits.
truncate public.members restart identity;

insert into public.members (name, power, inf, cav, arc) values
  ('Cryptic Angel', 218.7, '500-600', '500-600', '600-700'),
  ('Salles', 181.5, '400-500', '400-500', '500-600'),
  ('JoDee Monarch', 173.7, '300-400', '200-300', '400-500'),
  ('JC666', 171.8, '400-500', '400-500', '400-500'),
  ('IRØDZ', 170.0, '300-400', '300-400', '300-400'),
  ('IK33', 167.0, '400-500', '300-400', '400-500'),
  ('Toad', 152.3, '400-500', '400-500', '400-500'),
  ('Susu xu', 136.6, '300-400', '300-400', '400-500'),
  ('Yam', 127.6, '200-300', '200-300', '200-300'),
  ('DemonX', 126.6, '300-400', '200-300', '400-500'),
  ('老娘跑外送sharon', 123.9, '200-300', '200-300', '300-400'),
  ('SadieBear', 115.9, '200-300', '<200', '300-400'),
  ('Vestiskill', 115.8, '<200', '200-300', '200-300'),
  ('!!!Skill', 115.7, '200-300', '200-300', '200-300'),
  ('MKKnight', 114.4, '200-300', '200-300', '300-400'),
  ('nanya', 113.8, '200-300', '200-300', '300-400'),
  ('ThatWasntRedCard', 113.3, '300-400', '200-300', '300-400'),
  ('Baby', 112.7, '200-300', '200-300', '300-400'),
  ('Takeo', 111.8, '300-400', '200-300', '300-400'),
  ('F G R 1', 109.6, '200-300', '200-300', '200-300'),
  ('Twisted Biscuit', 108.0, '200-300', '<200', '200-300'),
  ('DemonXtra', 106.9, '200-300', '200-300', '300-400'),
  ('Hammelbock', 106.6, '200-300', '200-300', '300-400'),
  ('EpsonRolandXsj', 104.9, '200-300', '200-300', '200-300'),
  ('0VI The Bantai', 104.4, '200-300', '200-300', '200-300'),
  ('MH26 Kingdom', 103.3, '200-300', '200-300', '200-300'),
  ('Cvelle', 103.0, '<200', '<200', '200-300'),
  ('Leclerc', 101.4, '200-300', '<200', '300-400'),
  ('輕烏微微', 96.2, '200-300', '<200', '200-300'),
  ('DJshellz', 95.6, '<200', '<200', '200-300'),
  ('Sabo', 94.8, '<200', '<200', '200-300'),
  ('Neduts', 94.3, '200-300', '200-300', '200-300'),
  ('Fong', 93.8, '300-400', '300-400', '300-400'),
  ('JKGOM', 92.4, '<200', '<200', '<200'),
  ('RF POWER', 91.3, '200-300', '<200', '200-300'),
  ('Senol', 90.7, '200-300', '200-300', '200-300'),
  ('rey,salomon!', 90.2, '200-300', '200-300', '200-300'),
  ('Nisa15', 89.8, '200-300', '<200', '200-300'),
  ('TyLC', 88.7, '200-300', '200-300', '200-300'),
  ('WWW', 88.5, '200-300', '200-300', '200-300'),
  ('HELLHOUND', 87.4, '<200', '<200', '200-300'),
  ('mastergwyn', 86.3, '<200', '<200', '200-300'),
  ('AkazA', 84.6, '<200', '<200', '200-300'),
  ('Ancsika', 83.9, '<200', '<200', '200-300'),
  ('Cerkutay', 83.7, '200-300', '200-300', '200-300'),
  ('beske', 83.3, '<200', '-', '<200'),
  ('Rumiko', 79.1, '200-300', '200-300', '200-300'),
  ('Senis Ditron', 78.7, '<200', '<200', '200-300'),
  ('IFE', 76.9, '<200', '<200', '<200'),
  ('Araz Stark', 75.5, '200-300', '200-300', '200-300'),
  ('moon', 75.4, '<200', '<200', '<200'),
  ('Cat of War', 68.4, '<200', '<200', '<200'),
  ('Hercastillo91', 57.5, '<200', '<200', '<200'),
  ('PushingArtist6', 56.2, '200-300', '200-300', '200-300'),
  ('Peri', 55.4, '<200', '<200', '<200'),
  ('Champagne', 54.8, '<200', '<200', '<200');
